name = "osman-yagmur-portfolio"
main = "worker.js"
compatibility_date = "2024-01-01"

# Workers için varsayılan yapılandırma
# Account ID'nizi Cloudflare Dashboard'dan alabilirsiniz
# account_id = "YOUR_ACCOUNT_ID"

# Eğer custom domain kullanmak isterseniz:
# routes = [
#   { pattern = "example.com/*", zone_name = "example.com" }
# ]
